Lecture 7 scribbling added.
kuleshov/cornell-cs5785-2022-applied-ml pull request #4
Opened 2022-10-23 17:07 UTC by kojimano

2022-11-08 22:35 UTC, kuleshov requested changes
Thank you so much @kojimano! I added a few comments below for some things that would be great to tweak, but overall this is really good and I really like the structure.

2022-11-08 22:35 UTC, kuleshov commented on lecture-notes/lecture7-gaussian-discriminant-analysis.ipynb
> +    "After the introduction of generative modeling and Naive Bayes in the lecture, we will see the first example of generative models, namely Gaussian Discriminant Analysis.\n",
This is not quite accurate, we have already seen a first example of GMs (Naive Bayes), and you probably wanted to say "in the last lecture"

2022-11-08 22:35 UTC, kuleshov commented on lecture-notes/lecture7-gaussian-discriminant-analysis.ipynb
> +    "As a motivating problem for this lecture, we are going to use the Iris flower dataset ([R. A. Fisher, 1936](https://en.wikipedia.org/wiki/Ronald_Fisher)).\n",
We probably don't need that many small one-sentence paragraphs. We can merge some of these.

2022-11-08 22:35 UTC, kuleshov commented on lecture-notes/lecture7-gaussian-discriminant-analysis.ipynb
> +    "## 7.1.1 The Iris Flowers Dataset\n",
Small nitpick: Can we change this to X.Y.Z. (e.g., 7.1.1. with the dot) everywhere to be consistent with other lectures?

2022-11-08 22:35 UTC, kuleshov commented on lecture-notes/lecture7-gaussian-discriminant-analysis.ipynb
> +    "This objective is also often called the log-loss, or cross-entropy."
let's try to reduce the use one-sentence paragraphs a bit more, like here

2022-11-08 22:35 UTC, kuleshov commented on lecture-notes/lecture7-gaussian-discriminant-analysis.ipynb
> +    "### 7.2.1.1 review of distributions\n",
... could we use capital letters please?

2022-11-08 22:35 UTC, kuleshov commented on lecture-notes/lecture7-gaussian-discriminant-analysis.ipynb
> +    "Inuitively, the maximum likelihood class probabilities $\\phi$ should just be the class proportions that we see in the data. \n",
Can you please do a pass through the doc and change the style so that we don't have so many one-sentence paragraph. We would like to make it more like real set of notes.

Also "inuitively" -> "intuitively"

Any chance we could do a spell check on this please?

2022-11-08 22:35 UTC, kuleshov commented on lecture-notes/lecture7-gaussian-discriminant-analysis.ipynb
> +    "Taking the derivative and setting it to zero, we obtain \n",
We have a more detailed derivation of this in the notebook below. Could you please copy the material here so that the students have the full detailed derivation when they read the extended notes?
https://github.com/kuleshov/cornell-cs5785-2022-applied-ml/blob/main/slides/lecture17-midterm-review.ipynb

2022-11-08 22:35 UTC, kuleshov commented on lecture-notes/lecture7-gaussian-discriminant-analysis.ipynb
> +    "* __Type__: Supervised learning (multi-class classification)\n",
We want to add text here so it's not just bullet points, but more like a real set of lecture notes with full sentences and paragraphs. So we can keep the bullet point, but just write a sentence that describes what it is.

2022-11-08 22:35 UTC, kuleshov commented on lecture-notes/lecture7-gaussian-discriminant-analysis.ipynb
> +    "What are the differences between LDA/NB and logistic regession?\n",
Could we have a bit more full sentences please (not just bullet points)? (here and below)

2022-11-28 01:23 UTC, kojimano commented on lecture-notes/lecture7-gaussian-discriminant-analysis.ipynb
> +    "As a motivating problem for this lecture, we are going to use the Iris flower dataset ([R. A. Fisher, 1936](https://en.wikipedia.org/wiki/Ronald_Fisher)).\n",
I did merge small one-sentence paragraphs as much as I could throughout the note.

2022-11-28 01:23 UTC, kojimano commented on lecture-notes/lecture7-gaussian-discriminant-analysis.ipynb
> +    "After the introduction of generative modeling and Naive Bayes in the lecture, we will see the first example of generative models, namely Gaussian Discriminant Analysis.\n",
Fixed.

2022-11-28 01:23 UTC, kojimano commented on lecture-notes/lecture7-gaussian-discriminant-analysis.ipynb
> +    "## 7.1.1 The Iris Flowers Dataset\n",
Fixed.

2022-11-28 01:23 UTC, kojimano commented on lecture-notes/lecture7-gaussian-discriminant-analysis.ipynb
> +    "### 7.2.1.1 review of distributions\n",
Fixed.

2022-11-28 01:24 UTC, kojimano commented on lecture-notes/lecture7-gaussian-discriminant-analysis.ipynb
> +    "Taking the derivative and setting it to zero, we obtain \n",
I moved the notes from mid-term review.

2022-11-28 01:24 UTC, kojimano commented on lecture-notes/lecture7-gaussian-discriminant-analysis.ipynb
> +    "* __Type__: Supervised learning (multi-class classification)\n",
I added some sentences.

2022-11-28 01:24 UTC, kojimano commented on lecture-notes/lecture7-gaussian-discriminant-analysis.ipynb
> +    "What are the differences between LDA/NB and logistic regession?\n",
I added some sentences.

2023-02-01 04:54 UTC, kuleshov approved these changes
Thank you!

2023-02-01 04:54 UTC, merged