Scribe/lecture16
kuleshov/cornell-cs5785-2022-applied-ml pull request #5
Opened 2022-10-28 17:53 UTC by yair-schiff

Create lecture notes version for Lecture 16: Boosting

2022-11-08 23:55 UTC, kuleshov requested changes
Again, huge thanks @yair-schiff !

2022-11-08 23:55 UTC, kuleshov commented on lecture-notes/lecture16-boosting.ipynb
> +    "## 16.1.1. Underfitting\n",
Maybe these sections are a bit short?

2022-11-08 23:55 UTC, kuleshov commented on lecture-notes/lecture16-boosting.ipynb
> +    "4. Compute new data weights $w^{(i)} \\gets w^{(i)}\\exp[\\alpha_t \\mathbb{I}\\{y^{(i)} \\neq f(x^{(i)})\\} ]$.\n",
There is something funny with numbering.

Also, maybe we can provide some intuition about the math, e.g., if the error is zero, the weight becomes this, because that...

2022-11-08 23:55 UTC, kuleshov commented on lecture-notes/lecture16-boosting.ipynb
> +    "Visualizing the output of the algorithm, we see that it can learn a highly non-linear decision boundary to separate the two classes."
...that are useful to know about...

2022-11-08 23:55 UTC, kuleshov commented on lecture-notes/lecture16-boosting.ipynb
> +    "where we average models $P(y\\mid x,\\theta)$ using weights $P(\\theta \\mid \\mathcal{D})$."
something looks funny about the formatting or is it me?

2022-11-08 23:55 UTC, kuleshov commented on lecture-notes/lecture16-boosting.ipynb
> +    "## 16.4.1 Pros and Cons of Ensembling\n",
Maybe somehow merge these subsections? Somehow it doesn't quite read as a real text. I'm happy to also leave out pros/cons of ensembling if that's easier

2022-11-08 23:55 UTC, kuleshov commented on lecture-notes/lecture16-boosting.ipynb
> +    "## 16.5.2. Practical Considerations\n",
Maybe not make this a full paragraph? Add short introductory sentence?

2022-11-08 23:55 UTC, kuleshov commented on lecture-notes/lecture16-boosting.ipynb
> +    "Notice that the exponential loss very heavily penalizes (i.e., exponentially) misclassified points."
Maybe say why this is a problem?

2022-11-08 23:55 UTC, kuleshov commented on lecture-notes/lecture16-boosting.ipynb
> +    "### 16.5.3.2 Squared Loss\n",
missing dot after 2

2022-11-08 23:55 UTC, kuleshov commented on lecture-notes/lecture16-boosting.ipynb
> +    "Another common loss is the logistic loss, or log-loss as it's often called.\n",
Wouldn't log loss be a bit different?

2022-11-08 23:55 UTC, kuleshov commented on lecture-notes/lecture16-boosting.ipynb
> +    "## 16.5.4. Pros and Cons of Additive Models\n",
These two sections are a bit terse and short?

2022-11-08 23:55 UTC, kuleshov commented on lecture-notes/lecture16-boosting.ipynb
> +    "## 16.6.2 Another perspective on Boosting\n",
missing punctuation, not in title case, and maybe we could have a slightly better title here?

2022-11-08 23:55 UTC, kuleshov commented on lecture-notes/lecture16-boosting.ipynb
> +    "## 16.6.3 Revisiting Supervised Learning\n",
missing dot after 3, could we maybe re-check the doc for this?

2022-11-08 23:55 UTC, kuleshov commented on lecture-notes/lecture16-boosting.ipynb
> +    "$$ f : \\mathcal{X} \\to \\mathcal{Y} $$\n",
maybe don't need to have this inline?

2022-11-08 23:55 UTC, kuleshov commented on lecture-notes/lecture16-boosting.ipynb
> +    "But what do we mean by \"infinite-dimensional functions?\"\n",
Can we try to avoid one-sentence paragraph unless that actually represents the true logical structure of the text (one paragraph = one idea)?

2022-11-08 23:55 UTC, kuleshov commented on lecture-notes/lecture16-boosting.ipynb
> +    "Formally, the $x$-th entry of the vector $\\nabla J (f)$ is the partial derivative $\\frac{\\partial J(f)}{\\partial f(x)}$ of $J$ with respect to $f(x)$, the $x$-th component of $f$.\n",
Here, we might comment a bit on why?

Also, most sentences here are individual paragraphs, I think we should group them.

2022-11-08 23:55 UTC, kuleshov commented on lecture-notes/lecture16-boosting.ipynb
> +    "### 16.6.4.4. Supervised Learning Over Functions: Functional Gradient Descent\n",
Not sure if we need so many X.Y.Z.W. sub-sub-sub-sections, but I defer to you here

2022-11-08 23:55 UTC, kuleshov commented on lecture-notes/lecture16-boosting.ipynb
> +    "### 16.6.4.6. Modeling Functional Gradients\n",
This and the next subsection might even be taken out into a higher-level section? Your call

2022-11-15 02:57 UTC, yair-schiff commented on lecture-notes/lecture16-boosting.ipynb
> +    "## 16.1.1. Underfitting\n",
I combined all of these section under the heading `## 16.1.1. Underfitting and Boosting` and I used small bold headings for `#### Boosting` and `#### Weak Learners`. 

Let me know if that looks better.

2022-11-15 03:32 UTC, yair-schiff commented on lecture-notes/lecture16-boosting.ipynb
> +    "4. Compute new data weights $w^{(i)} \\gets w^{(i)}\\exp[\\alpha_t \\mathbb{I}\\{y^{(i)} \\neq f(x^{(i)})\\} ]$.\n",
>There is something funny with numbering.

Are you referring to this:
```
3. 1. Compute model weight $\alpha_t = \log[(1-e_t)/e_t]$.
 2. Set $f \gets f + \alpha_t g_t$.
```

I wrote it that way so that it would show up as A and B steps:
<img width="560" alt="Screen Shot 2022-11-14 at 10 05 25 PM" src="https://user-images.githubusercontent.com/35781889/201816649-632670bd-a6b5-4113-9356-1974b44d67c1.png">

Or was there a different numbering issue?

2022-11-15 03:33 UTC, yair-schiff commented on lecture-notes/lecture16-boosting.ipynb
> +    "4. Compute new data weights $w^{(i)} \\gets w^{(i)}\\exp[\\alpha_t \\mathbb{I}\\{y^{(i)} \\neq f(x^{(i)})\\} ]$.\n",
>Also, maybe we can provide some intuition about the math, e.g., if the error is zero, the weight becomes this, because that..

I added this bullet. Let me know what you think
```
* Notice that $e_t$ intuitively measures how much *influence* $g_t$ should have on our overall predictor $f$.
As $e_t$ approaches zero, meaning few of the highly weighted points were misclassified by $g_t$, $\alpha_t$ will be large, allowing $g_t$ to have a bigger contribution to our predictor.
As $e_t$ approaches 1/2 (recall that $g_t$'s are 'weak learners'), this means that $g_t$ is not doing much better than random guessing.
This will cause $\alpha_t$ to be close to zero, meaning that $g_t$ is contributing little to our overall prediction function.
```

2022-11-15 03:33 UTC, yair-schiff commented on lecture-notes/lecture16-boosting.ipynb
> +    "4. Compute new data weights $w^{(i)} \\gets w^{(i)}\\exp[\\alpha_t \\mathbb{I}\\{y^{(i)} \\neq f(x^{(i)})\\} ]$.\n",
@kuleshov, I think I might have noticed a typo in step 2 of Adaboost definition:
```
$e_t = \frac{\sum_{i=1}^n w^{(i)} \mathbb{I}\{y^{(i)} \neq f(x^{(i)})\}}{\sum_{i=1}^n w^{(i)}}$
```

Should $f$ be $g_t$ here instead?

2022-11-15 03:46 UTC, yair-schiff commented on lecture-notes/lecture16-boosting.ipynb
> +    "Visualizing the output of the algorithm, we see that it can learn a highly non-linear decision boundary to separate the two classes."
Fixed below

2022-11-15 03:47 UTC, yair-schiff commented on lecture-notes/lecture16-boosting.ipynb
> +    "where we average models $P(y\\mid x,\\theta)$ using weights $P(\\theta \\mid \\mathcal{D})$."
I am not sure why the latex symbols are being double escaped on this comment on Github, but in the actual notebook I'm not seeing any issues:
```
There are other approaches to ensembling that are useful to know about.
* In stacking, we train $m$ independent models $g_j(x)$ (possibly from different model classes) and then train another model $f(x)$ to predict $y$ from the outputs of the $g_j$.
* The Bayesian approach can also be seen as form of ensembling
$$ P(y\mid x) = \int_\theta P(y\mid x,\theta) P(\theta \mid \mathcal{D}) d\theta $$
where we average models $P(y\mid x,\theta)$ using weights $P(\theta \mid \mathcal{D})$.
```

2022-11-15 03:55 UTC, yair-schiff commented on lecture-notes/lecture16-boosting.ipynb
> +    "## 16.4.1 Pros and Cons of Ensembling\n",
I combined these into a single slide with no header and made the flow more text-like. Let me know what you think

2022-11-15 04:05 UTC, yair-schiff commented on lecture-notes/lecture16-boosting.ipynb
> +    "Another common loss is the logistic loss, or log-loss as it's often called.\n",
I removed this comment

2022-11-15 04:11 UTC, yair-schiff commented on lecture-notes/lecture16-boosting.ipynb
> +    "## 16.5.4. Pros and Cons of Additive Models\n",
Cut both sections and replaced with this slide:
```
To summarize what we have seen for additive models:
* Additive models have the form
$$ f(x) = \sum_{t=1}^T \alpha_t g(x; \phi_t). $$
* These models can be fit using the forward stagewise additive approach.
* This reproduces Adaboost (when using exponential loss) and can be used to derive new boosting-type algorithms that optimize a wide range of objectives that are more robust to outliers and extend beyond classification.
 ```

2022-11-15 04:12 UTC, yair-schiff commented on lecture-notes/lecture16-boosting.ipynb
> +    "## 16.6.2 Another perspective on Boosting\n",
What do you think about `## 16.6.2. Motivating Gradient Boosting`?

2022-12-14 04:54 UTC, kuleshov reviewed
Thank you, Yair! I added some comments below. When you think it's ready, let me know, I'll do one last reviewing pass and then merge.

2022-12-14 04:54 UTC, kuleshov commented on lecture-notes/lecture16-boosting.ipynb
> +    "4. Compute new data weights $w^{(i)} \\gets w^{(i)}\\exp[\\alpha_t \\mathbb{I}\\{y^{(i)} \\neq f(x^{(i)})\\} ]$.\n",
Yes, you're probably right about the typo

2022-12-14 04:54 UTC, kuleshov commented on lecture-notes/lecture16-boosting.ipynb
> +    "4. Compute new data weights $w^{(i)} \\gets w^{(i)}\\exp[\\alpha_t \\mathbb{I}\\{y^{(i)} \\neq f(x^{(i)})\\} ]$.\n",
For the numbering, I think I see the numbers being nor ordered as 1, 2, 3, 4...

2022-12-14 04:54 UTC, kuleshov commented on lecture-notes/lecture16-boosting.ipynb
> +    "where we average models $P(y\\mid x,\\theta)$ using weights $P(\\theta \\mid \\mathcal{D})$."
Okay, sounds good then. Is there a way to fix it in both (maybe by making it like other parts of the notebook that don't have this problem)? If not, no worries.

2022-12-14 04:54 UTC, kuleshov commented on lecture-notes/lecture16-boosting.ipynb
> +    "### 16.6.4.4. Supervised Learning Over Functions: Functional Gradient Descent\n",
If we can combine these small bullet points into a more "flowing" text, that would be great, but no worries if we need to prioritize other stuff

2022-12-14 04:54 UTC, kuleshov commented on lecture-notes/lecture16-boosting.ipynb
> +    "## 16.4.1 Pros and Cons of Ensembling\n",
thanks!

2022-12-15 15:36 UTC, yair-schiff commented on lecture-notes/lecture16-boosting.ipynb
> +    "4. Compute new data weights $w^{(i)} \\gets w^{(i)}\\exp[\\alpha_t \\mathbb{I}\\{y^{(i)} \\neq f(x^{(i)})\\} ]$.\n",
> There is something funny with numbering.
> 
> Also, maybe we can provide some intuition about the math, e.g., if the error is zero, the weight becomes this, because that...

I see. For some reason as `.ipynb` this looks ok to me, but when I download the file as Reveal.js slides, I am also seeing that all the numbers are `1.` so I changed each slide fragment to be: 
```
**Step 1:** ...
**Step 2:** ...
...
```

2022-12-15 16:20 UTC, yair-schiff commented on lecture-notes/lecture16-boosting.ipynb
> +    "where we average models $P(y\\mid x,\\theta)$ using weights $P(\\theta \\mid \\mathcal{D})$."
@kuleshov Can you add a screenshot of what you're seeing here that's off?

This is what I see when I export these to `slides.html`
![Screen Shot 2022-12-15 at 11 19 37 AM](https://user-images.githubusercontent.com/35781889/207913078-7c4be918-828a-4717-9bbb-99dbab828508.png)

2023-02-01 04:54 UTC, kuleshov approved these changes
Thank you!

2023-02-01 04:54 UTC, merged