Scribe/lecture15
kuleshov/cornell-cs5785-2022-applied-ml pull request #6
Opened 2022-10-28 17:53 UTC by yair-schiff

Create lecture notes version for Lecture 15: Decision Trees

2022-10-28 17:56 UTC, yair-schiff commented
@kuleshov, I am having an issue reproducing the ensemble of polynomial regression curves from the slides and could use some help debugging why my plot (green ensemble curve specifically) is not matching that from the `slides`
Lecture notes: 
![ensemble](https://user-images.githubusercontent.com/35781889/198701400-8fd2f99a-d815-428c-958e-95199d98996d.png)

Slides:
![ensemble_slides](https://user-images.githubusercontent.com/35781889/198701643-4c5a32f5-bd27-473b-85e8-bed82271dd74.png)

2022-11-08 22:39 UTC, kuleshov commented
@yair-schiff Ah, yes, I think I played around with various data samples and chose one that illustrated my point. Is there any chance you could try a few different seeds and see if there's one that gives you something a bit more sensible?

2022-11-08 22:58 UTC, kuleshov requested changes
Huge thanks, this is really really good! I left some small comments

2022-11-08 22:58 UTC, kuleshov commented on lecture-notes/lecture15-decision-trees.ipynb
> +    "The visualied output above depicts the process by which our trained decision tree classifier makes predictions.\n",
Small typo in "visualied"

2022-11-08 22:58 UTC, kuleshov commented on lecture-notes/lecture15-decision-trees.ipynb
> +    "The next important concept in decision tress is that to **decision regions**.\n",
Small typo here too. Any chance you could quickly run this through a spell checker?

2022-11-08 22:58 UTC, kuleshov commented on lecture-notes/lecture15-decision-trees.ipynb
> +    "* Top left: regions that cannot be represented by a tree\n",
Maybe we could just expand on these bullet points a bit and add one short sentence here to explain why one of these regions cannot be defined using a decision tree?

2022-11-08 22:58 UTC, kuleshov commented on lecture-notes/lecture15-decision-trees.ipynb
> +    "$$ \\min_{r \\in \\mathcal{U}} \\left( \\underbrace{L(\\{(x, y) \\in \\mathcal{D} \\mid r(x) = \\text{T}\\})}_\\text{left subtree} +  \\underbrace{L(\\{(x, y) \\in \\mathcal{D} \\mid r(x) = \\te
Ah, sorry, I forgot to ping you about this earlier. I made some tweaks to the notation/explanation used in this section. Is there any chance you could update this part with the latest changes in the slides notebook?
https://github.com/kuleshov/cornell-cs5785-2022-applied-ml/blob/main/slides/lecture15-decision-trees.ipynb

2022-11-08 22:58 UTC, kuleshov commented on lecture-notes/lecture15-decision-trees.ipynb
> +    "## 15.2.2. Objectives for Trees\n",
Same for this section. I swapped the order of the subsections and added a few more clarifications that hopefully make this clearer.

2022-11-08 22:58 UTC, kuleshov commented on lecture-notes/lecture15-decision-trees.ipynb
> +    "## 15.2.3. Other Practical Considerations\n",
This is a super short section, maybe we could fold this into the above section?

2022-11-08 22:58 UTC, kuleshov commented on lecture-notes/lecture15-decision-trees.ipynb
> +    "### 15.3.1.1. Fitting High-Degree Polynomials\n",
It looks like we were able to get slightly better dataset samples here? Maybe we can record this seed (or one that gives similar results)

2022-11-08 22:58 UTC, kuleshov commented on lecture-notes/lecture15-decision-trees.ipynb
> +    "This phenomenon seen above is also known as the high-variance problem, which can be summarized as follows: Each small subset on which we train yields a very different model."
punctuation and we should probably say "high-variance" if it's used as an adjective and otherwise just "high variance"

2022-11-08 22:58 UTC, kuleshov commented on lecture-notes/lecture15-decision-trees.ipynb
> +    "## 15.3.3. Example: Bagged Polynomial Regression\n",
Maybe make this a subsection of the previous section? (small nitpick, can also leave as is)

2022-11-08 22:58 UTC, kuleshov commented on lecture-notes/lecture15-decision-trees.ipynb
> +    "## 15.3.4. Extensions of Bagging\n",
15.3.4 and 15.3.5. are really short, maybe tweak the strucutre a bit / merge them?

2022-11-08 22:58 UTC, kuleshov commented on lecture-notes/lecture15-decision-trees.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAtAAAAEJCAYAAAC9jhDmAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjEsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+
small typo here

2022-11-10 18:33 UTC, yair-schiff commented on lecture-notes/lecture15-decision-trees.ipynb
> +    "The visualied output above depicts the process by which our trained decision tree classifier makes predictions.\n",
Thanks for catching! Fixed this (also installed a spellchecker to notebooks to catch the other ones below)

2022-11-10 19:03 UTC, yair-schiff commented on lecture-notes/lecture15-decision-trees.ipynb
> +    "* Top left: regions that cannot be represented by a tree\n",
Adding the following, let me know what you think:
```
Setting aside the top left image for a moment, the other 3 depictions from Hastie et al. show how we can visualize decision trees.
For an input space of two features $X_1, X_2$, we first have the actual tree, similar to what we've seen thus far (bottom left).
This tree has a maximum depth of 3 and first splits the inputs along the $X_1$ dimension.
On the left branch we have one more internal decision node based on values of $X_2$ resulting in 2 leaf nodes that each correspond to a region of the input space.
On the right branch of the tree, we see two more decision nodes that result in an additional 3 leaf nodes, each corresponding to a different region.
Note that as mentioned above, rather than using more complicated decision rules such as $t_1 < X_1 \leq t_3$, we can separate this into 2 sequential and simpler decisions, as seen by the root node and the first decision node to its right.

We can equivalently view this decision tree in terms of how it partitions the input space (top right image).
Note that each of the partition lines on the $X_1$ and $X_2$ axes correspond to our decision nodes and the partitioned regions correspond to the leaf nodes in the tree depicted in the bottom left image.

Finally, if each region corresponds to a predicted value for our target, then we can draw these decision regions with their corresponding prediction values on a third axis (bottom right image).

Returning to the top left image, this image actually depicts a partition of the input space that would not be possible using decision trees, which highlights the point that not every partition corresponds to a decision tree.
Specifically, for this image the central region that is non-rectangular cannot be created from a simple branching procedure of a decision tree.
```

Not sure if the sentence explaining why top left is not possible as a decision tree is clear enough. Would appreciate your feedback on that

2022-11-10 19:53 UTC, yair-schiff commented on lecture-notes/lecture15-decision-trees.ipynb
> +    "### 15.3.1.1. Fitting High-Degree Polynomials\n",
I think I was able to get some good results. This is with `np.random.seed(0)`
![seed0_init](https://user-images.githubusercontent.com/35781889/201192930-a4656d09-5a98-4d1a-8ca1-1162c148e5bd.png)
![seed0_ex](https://user-images.githubusercontent.com/35781889/201192935-5f930d81-be66-4492-b694-ee9acfc77a1a.png)
![seed0](https://user-images.githubusercontent.com/35781889/201192941-dc7aad47-5b81-4310-9388-b2d88ecb0417.png)

2022-11-11 01:17 UTC, yair-schiff commented on lecture-notes/lecture15-decision-trees.ipynb
> +    "## 15.3.4. Extensions of Bagging\n",
Moved 15.3.4 to end of 15.3.2 and left the "Summary" as a regular slide at the end of the example without its own section title.

2022-12-14 04:54 UTC, kuleshov commented on lecture-notes/lecture15-decision-trees.ipynb
> +    "* Top left: regions that cannot be represented by a tree\n",
sounds great!

2022-12-14 04:55 UTC, kuleshov commented on lecture-notes/lecture15-decision-trees.ipynb
> +    "### 15.3.1.1. Fitting High-Degree Polynomials\n",
great!

2022-12-14 04:55 UTC, kuleshov commented on lecture-notes/lecture15-decision-trees.ipynb
> +    "## 15.3.4. Extensions of Bagging\n",
great

2022-12-14 04:55 UTC, kuleshov approved these changes
Looks good to me!

2022-12-14 04:56 UTC, merged